opt_out_usage
default_platform(:android)

platform :android do
  desc "Deploy a new version to Google Play Store"
  lane :deploy do
    # https://docs.fastlane.tools/advanced/fastlane/#directory-behavior
    version_code = File.read("../app/build.gradle.kts")[/^\s*versionCode\s*=\s*(\d+)/, 1]
    UI.user_error!("Could not extract versionCode") if version_code.nil?
    UI.message("Using version code #{version_code}")

    gradle(task: "assembleRelease bundleRelease")
    upload_to_play_store(
        track: 'production',
        release_status: 'completed',
        version_code: version_code.to_i,
        aab: 'app/build/outputs/bundle/release/app-release.aab',
        skip_upload_apk: true,
        skip_upload_metadata: true,
        skip_upload_changelogs: true,
        skip_upload_images: true,
        skip_upload_screenshots: true,
      )
  end
end
